INSERT INTO value_units (measurement, unit)
VALUES ('temperature', 'fahrenheit')
     , ('temperature', 'celsius')
     , ('airflow', 'feet^3 minute^-1')
;

-- The values below are the first pass at figuring out all the
-- possible enum types. (We're ignoring `TIME` entirely for now.)
INSERT INTO value_types (label, type)
VALUES ('Boolean', 'true')
     , ('Integer', '1')
     , ('Float', '1.0')
     , ('Default LDO', '["OFF", "ON"]')
     , ('Default LDI', '["OFF", "ON"]')
     , ('DAY_NIGHT', '["OFF", "ON"]')
     , ('OFF_ON', '["OFF", "ON"]')
     , ('ZONE_MODE', '["VAC", "OCC1", "OCC2", "OCC3", "OCC4", "OCC5", "WARMUP", "COLLDOWN", "NGHT_HTG", "STOP_HTG", "STOP_CLG"]')
     , ('Default L2SL', '["OFF", "ON"]')
     , ('EQS_OFF_ONI', '["OFF", "ON"]')
     , ('DISABL_ENABL', '["DISABL", "ENABLE"]')
     , ('OK_FAULT', '["OK", "FAULT"]')
     , ('NO_RESET', '["NO", "RESET"]')
     , ('STOP_RUN', '["STOP", "RUN"]')
     , ('COOL_HEAT', '["COOL", "HEAT"]')
     , ('Generic_-5011', '["DISABLE", "ENABLE"]')
     , ('UNOCC_OCC', '["UNOCC", "OCC"]')
     , ('LOCAL_REMOTE', '["LOCAL", "REMOTE"]')
     , ('NO_YES', '["NO", "YES"]')
     , ('Generic_-5014', '["NO", "FLOW"]')
     , ('boolean', '["FALSE", "TRUE"]')
     , ('ONE_TWO', '["ONE", "TWO"]')
     , ('Generic_-5008', '["OK", "ALARM"]')
     , ('Generic_-5007', '["AUTO", "HAND"]')
     , ('Generic_-5010', '["INACTIVE", "READY"]')
     , ('Generic_-5001', '["INACTIVE", "DRIVE"]')
     , ('Generic_-5003', '["AUTO", "QUIET", "WEAK", "STRONG", "5"]')
     , ('Generic_-5004', '["AUTO", "2", "3", "4", "5", "6", "SWING"]')
     , ('Generic_-5005', '["DEG", "DEG"]')
     , ('Generic_-5002', '["HEAT", "DRY", "COOL", "FAN", "AUTO"]')
     , ('REC_HX_PUMP_LEAD', '["P2", "P1"]')
     , ('CLOSED_OPEN', '["CLOSED", "OPEN"]')
     , ('NORMAL_ALARM', '["NORMAL", "ALARM"]')
     , ('STOP_START', '["STOP", "START"]')
     , ('ENABLE_DISABL', '["ENABLE", "DISABL"]')
     , ('BACNET LENUM', '["NIGHT", "DAY", "SPECIAL2", "SPECIAL3", "SPECIAL4", "SPECIAL5"]')
     , ('SSTO_OPERATION', '["NONE", "HEATING", "COOLING", "BOTH"]')
     , ('STOP_MODE', '["STOP_HTG", "STOP_CLG", "STOP_HOC", "NO_STOP"]')
     , ('START_MODE', '["STRT_HTG", "STRT_CLG", "NO_STRT"]')
     , ('RESET_HERE', '["RESET", "ALARM"]')
     , ('Generic_2002', '["Stopped", "Running"]')
     , ('Generic_2001', '["No", "Yes"]')
     , ('Generic_2000', '["Off", "On"]')
     , ('BACNET EVENT ENROLLMENT', '["NRML", "FAULT", "OFFNRML", "HIGH", "LOW"]')
     , ('NTRAL_ACTIVE', '["NTRAL", "ACTIVE"]')
     , ('NEG_POS', '["NEG", "POS"]')
     , ('LO_HI', '["LO", "HI"]')
     , ('HOLD_FILL', '["HOLD", "FILL"]')
     , ('BLEED_HOLD', '["No", "Yes"]')
     , ('OCC_UNOCC', '["OCC", "UNOCC"]')
     , ('NIGHT_DAY', '["NIGHT", "DAY"]')
     , ('ON_OFF', '["ON", "OFF"]')
     , ('CLEAN_DIRTY', '["CLEAN", "DIRTY"]')
     , ('ETS_STE', '["ETS", "STE"]')
     , ('OPEN_CLOSED', '["OPEN", "CLOSED"]')
     , ('Default L2SP', '["OFF", "ON"]')
     , ('VFD SAFETY', '["NORMAL", "LOCKOUT"]')
     , ('SS PUMP LL', '["P1", "P2", "P3"]')
     , ('OPERATION_PHASE', '["OFF", "HTDURVAC", "CLDURVAC", "STRT_HTG", "REGULATG", "STOP_HTG", "STOP_CLG", "POST_HTG", "POST_CLG"]')
     , ('NORMAL_FAIL', '["NORMAL", "FAIL"]')
     , ('CHLR45', '["CH", "CH"]')
     , ('NORMAL_LOCKOUT', '["NORMAL", "LOCKOUT"]')
     , ('LOAD_SHED', '["NONE", "STAGE", "STAGE", "STAGE"]')
     , ('CHLR_SEQ', '["0", "1", "2", "3", "4", "5", "43", "53", "54", "543"]')
;